config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :addresses
  
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  helper_method :collection
  def new
    run Address::Operation::New
    render cell(Address::Cell::New, @form), layout: false
  end

  def create
    params_addres =  ActiveSupport::HashWithIndifferentAccess.new(params[:address].permit!) || {}
    operation = Address::Operation::Create.(params: { data: params_addres })
    unless operation.success?
      # render :new
    else
      redirect_to addresses_path
    end
  end

  def edit
    run Address::Operation::Edit
    render cell(Address::Cell::Edit, @form), layout: false
  end

  def update
    params_addres =  ActiveSupport::HashWithIndifferentAccess.new(params[:address].permit!) || {}
    operation = Address::Operation::Update.(params: { id: params[:id], data: params_addres})
    unless operation.success?
      # render :edit
    else
      redirect_to addresses_path
    end
  end

  def destroy
    run Address::Operation::Delete

    redirect_to addresses_path
  end


  private

  def collection
    @collection ||= Address.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/index.html.haml
%h1 Address#Index

= link_to "Agregar", new_address_path
%table{border: 1}
  %thead
    %tr
      %th Nombre
      %th Ubicacion
      %th Estado
      %th Pais
      %th Telefono 1
      %th Telefono 2
      %th
  %tbody
    - unless collection.blank?
      - collection.each do |address|
        %tr
          %td= address.name
          %td= address.location
          %td= address.state_id
          %td= address.country_id
          %td= address.phone
          %td= address.phone_2
          %td
            = link_to "Editar", edit_address_path(address)
            = link_to "Eliminar", address_path(address), method: :delete, data: {confirm: "Estas seguro?"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTrailblazer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>